networks:
  myschoolapinet:    
services:
  myschooldb:
    container_name: my-school-db
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - 8082:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password@12345
    networks:
      - myschoolapinet
  myschool.api.host:
    container_name: my-school-api
    image: ${DOCKER_REGISTRY-}myschoolapi
    build:
      context: .
      dockerfile: MySchool.Api.Host/Dockerfile
    ports:
      - 8081:8080
    depends_on: 
      - myschooldb
    environment:
      - DB_HOST=myschooldb
      - DB_NAME=MySchoolDB
      - DB_SA_PASSWORD=Password@12345
    networks:
      - myschoolapinet
